version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=bismillah123
      - DB_NAME=event_management
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USER=your-mailtrap-user
      - SMTP_PASS=your-mailtrap-pass
      - SERVER_URL=http://10.10.11.28:3000
      - TZ=Asia/Jakarta
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FROM_EMAIL=${FROM_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - USE_BREVO=${USE_BREVO}
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/tickets:/app/public/tickets
      - ./public/certificates:/app/public/certificates
      - ./public/generated-tickets:/app/public/generated-tickets
    networks:
      - event-network
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: bismillah123
      MYSQL_DATABASE: event_management
      TZ: Asia/Jakarta
    command: --default-time-zone='+00:00'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - event-network
    
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: bismillah123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - event-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mysql_data:

networks:
  event-network:
    driver: bridge